from pydantic import BaseModel, Field
from typing import Annotated, Literal, Optional, List, Any
from operator import add


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the agent")
    user_question: str = Field(default="", description="The original question asked by the user")
    curated_ques: str = Field(default="", description="Curated user question")
    prompt_query_context: str = Field(default="", description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query: str = Field(default="", description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe: Literal["Yes", "No", "Pending"] = Field(default="Pending", description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(default="", description="Comments regarding the safety of the generated SQL query")
    approval_status: Literal["pending", "approved", "rejected", "modified"] = Field(default="pending", description="Human-in-the-Loop approval status")
    user_feedback: str = Field(default="", description="Human operator feedback or overrides")
    sql_query_execution_result: str = Field(default="", description="The result of executing the generated SQL query on the database")
    final_answer: str = Field(default="", description="The final answer generated by the agent based on the SQL query execution result and the curated question")


class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments: str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")


class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the ETL agent")
    approval_status: Literal["pending", "approved", "rejected"] = Field(default="approved", description="HITL approval state for ETL tools")
    user_feedback: str = Field(default="", description="Human operator feedback for ETL pipeline")


class RouterSchema(BaseModel):
    answer: Literal["sql", "etl"] = Field(..., description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(default="", description="Additional comments or feedback regarding the classification of the user's question")


class DataAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(default_factory=list, description="List of messages to be processed by the Data agent")
    route_response: str = Field(default="", description="The response from the router indicating whether to route to SQL or ETL operations")
    approval_status: Literal["pending", "approved", "rejected", "modified"] = Field(default="pending", description="HITL approval status")
    pending_approval: Optional[Dict[str, Any] if False else Any] = Field(default=None, description="Metadata about the action awaiting human approval")